
dependencies {
	     implementation project(':projects:extensions:jpanlib')
	     implementation project(':projects:extensions:joern-fuzzyc')
	     implementation project(':projects:extensions:joern')

		 implementation project(':projects:octopus')
		 implementation 'org.json:json:20141113'
         implementation 'org.slf4j:slf4j-api:1.7.13'
}
